sudo: false
language: rust
rust:
  - 1.15.0
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
before_script:
  - wget https://github.com/jedisct1/libsodium/releases/download/1.0.8/libsodium-1.0.8.tar.gz &&
    tar xvfz libsodium-1.0.8.tar.gz &&
    cd libsodium-1.0.8 && ./configure --prefix=$HOME/installed_libsodium && make && make install &&
    cd ..
  - export PKG_CONFIG_PATH=$HOME/installed_libsodium/lib/pkgconfig:$PKG_CONFIG_PATH &&
    export LD_LIBRARY_PATH=$HOME/installed_libsodium/lib:$LD_LIBRARY_PATH
  - |
    pip install 'travis-cargo<0.2' --user &&
    export PATH=$HOME/.local/bin:$PATH
  - cargo install --force cargo-audit
script:
  - |
    travis-cargo build &&
    travis-cargo test &&
    travis-cargo bench &&
    cargo audit &&
    travis-cargo --only stable doc
after_success:
  - travis-cargo --only stable doc-upload
env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=dev
    - secure: jBMjbTNdE+P6D2MNLcc1zJ3KBTepo4Jdge+yRkuVRCd2jNskEiweKhWyvqiChy4ZUbLD/lAJmAu83RgXqnG7jZbUHs74KKkrL5/tNFJeLoCg2jenygrm0jy/ZjMUWUgWTBeZuT1cpUQE4XIp5081DoefuVQ5Duu77gE0vw3YoFWqfwijwmbVsh1626cfKBgLPaqp0AWgRVG0KABVpPg3MBSS0MsPV1GYbjx+jYfhxX0gzEmCrxqwjAoRuUrSeOuD9+LZvMXMIwiRBijEtBx/SWq/n2GfkhlDjyajznbC8R1J8gpLPhhwNNq3E4hAHZnSkF/Y4qUuHiT6BRf/7DFMxg6C1BgEFhOJRcgUS9XBA6FQ4d3E9M/oa2krJYvbGb6RMKckEy3Zy3MpbjipqfBsWhQnkGNydyvZ0vsgk27iUNM3ooyBqZoXKWKwUjQ1RmZD5XNjvUJzIt5eOJG2h5AVMuyaGjSLR4Y1rX3A+xJpouRmxIoJTbtqMIUKXr9Qwd9LuXRqzKYbYndqKXaHGwaO9KPa34w4vJaBJUhj4shySIJmuMdevvSFpVc86JKuLC8APUeyG0yWgRZdKL5Lpcel6ZGsuWD5oTIgZ0OSRqX9DKoHmKtg9o0A6CSo0dccmeyfXO7EogKh2n3J+Od89bIX0FuskPFqSvzqhEud6QW2POg=
